name: Update Rates Daily
on:
  schedule:
    - cron: '30 14 * * *' # 9:30 AM CST (14:30 UTC)
  workflow_dispatch: # Add this!
jobs:
  update-rates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          curl -X GET "https://lcfrafedxrevtrhymmhu.functions.supabase.co/fetch-rates" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}"